<?php
/**
 * Plugin Name: Bunz Hide Notices
 * Plugin URI: https://github.com/bunz80/bunz-hide-notices
 * Description: Hides all admin area notifications and alerts generated by other plugins for a cleaner dashboard.
 * Version: 1.0.0
 * Author: Salvatore Pisai for SerpicoADV
 * Author URI: https://github.com/bunz80
 * License: GPLv2 or later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain: bunz-hide-notices
 */

// Prevent direct access to the file
defined( 'ABSPATH' ) or die( 'No script kiddies please!' );

// Hook into the 'admin_enqueue_scripts' action to load our custom CSS at the right time
add_action('admin_enqueue_scripts', 'bunz_hide_notices_css');

/**
 * Enqueue custom CSS to hide admin notices and alerts.
 */
function bunz_hide_notices_css() {
    // Custom CSS to hide notices
    $custom_css = "
        .notice, .update-nag, .updated, .error, .is-dismissible {
            display: none !important;
        }
    ";

    // Register a custom style to use with wp_add_inline_style
    wp_register_style('bunz-hide-notices-custom', false);
    wp_enqueue_style('bunz-hide-notices-custom');

    // Safely add inline CSS
    wp_add_inline_style('bunz-hide-notices-custom', $custom_css);
}

// Ensure the text domain is loaded for translation
add_action( 'init', 'bunz_hide_notices_load_textdomain' );

/**
 * Load plugin text domain for translations.
 */
function bunz_hide_notices_load_textdomain() {
    load_plugin_textdomain( 'bunz-hide-notices', false, basename( dirname( __FILE__ ) ) . '/languages' );
}

?>
