<?php
/**
 * Plugin Name: Bunz Hide Notices
 * Plugin URI: https://github.com/bunz80/bunz-hide-notices
 * Description: A simple plugin to hide all notifications and alerts generated by other plugins in the WordPress admin area. Ideal for creating a cleaner dashboard experience.
 * Version: 1.0.0
 * Author: Salvatore Pisai for SerpicoADV
 * Author URI: https://github.com/bunz80
 * License: GPL2 or later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain: bunz-hide-notices
 */

// Hook into the 'admin_enqueue_scripts' action to load our custom CSS at the right time
add_action('admin_enqueue_scripts', 'bunz_hide_notices_css');

/**
 * Enqueue custom CSS to hide admin notices and alerts.
 */
function bunz_hide_notices_css() {
    // Add inline CSS to hide notices, using wp_add_inline_style for better practices
    $custom_css = "
        .notice, .update-nag, .updated, .error, .is-dismissible {
            display: none !important;
        }
    ";
    
    // Check if the admin style is already enqueued to ensure compatibility
    if ( wp_style_is( 'wp-admin', 'enqueued' ) ) {
        wp_add_inline_style( 'wp-admin', $custom_css );
    } else {
        // If the admin style isn't enqueued, we'll print the CSS directly as a fallback
        echo '<style>' . $custom_css . '</style>';
    }
}

// Ensure the text domain is loaded for translation
add_action( 'init', 'bunz_hide_notices_load_textdomain' );

/**
 * Load plugin text domain for translations.
 */
function bunz_hide_notices_load_textdomain() {
    load_plugin_textdomain( 'bunz-hide-notices', false, basename( dirname( __FILE__ ) ) . '/languages' );
}
?>
